// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Daniel_Riege_WWDC23",
    platforms: [
        .iOS("16")
    ],
    products: [
        .iOSApplication(
            name: "Daniel_Riege_WWDC23",
            targets: ["AppModule"],
            bundleIdentifier: "com.danielriege.WWDC23",
            teamIdentifier: "9ZB2Q72U8X",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .car),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .developerTools
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("PrivateResources")
            ]
        )
    ]
)